version: "3"

networks:
  services:
    ipam:
      config:
        - subnet: 173.17.0.0/24

services:
  # Agents

  issuer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ISSUER_SEED=000000000000000000000000Trustee1
        - ISSUER_AGENT_ENDPOINT=http://173.17.0.100:8000
        - ISSUER_WALLET_KEY=Xaff17iH1MNc
        - ISSUER_ADMIN_API_KEY=secret
        - ISSUER_HOSTNAME=173.17.0.100
        - GENESIS_URL=http://vonx.pocquebec.org:9000/genesis
        - INBOUND_PORT=8000
        - API_PORT=3000
    ports:
      - 3000:3000
      - 8000:8000
    networks:
      services:
        ipv4_address: 173.17.0.100
